# Generated by Django 4.1.3 on 2022-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='roomNo',
            field=models.IntegerField(default=1),
        ),
    ]
