# Generated by Django 4.1.3 on 2022-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbook', '0002_rooms_floor_rooms_roomno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.CharField(default='Enter Your Room Details Here', max_length=100),
        ),
    ]
