# Generated by Django 4.1.3 on 2022-11-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbook', '0003_rooms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(default='Enter Your Room Details Here', max_length=500),
        ),
    ]
