# Generated by Django 4.1.3 on 2022-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbook', '0005_alter_rooms_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
