# Generated by Django 4.1.3 on 2022-11-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbook', '0006_rooms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
