# Generated by Django 4.1.3 on 2022-11-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbook', '0008_remove_rooms_image2_remove_rooms_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='post',
            new_name='rooms',
        ),
    ]
